### ISSUE TITLE
Ластик

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-9-vector-editor#42]
Поправьте пожалуйста ластик, уж с очень большим отставанием он стирает.

**Comment by SyrbuDmitry** [comment]
Для того чтобы ластик стирал, необходимо точное наведение на участок и чтобы браузер зарегистрировал координаты мыши при перемещении курсора. Проблема с отставанием  
связана с особенностями регистрации браузером курсора.
